Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Models/BlogPost.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BloggingPlatformApplication.Models
{
    public class BlogPost
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "please enter title..")]
        public string Title { get; set; }

        [Required(ErrorMessage = "please enter Description..")]
        [MinLength(10, ErrorMessage = "Please describe 10words atleast..")]
        public string Content { get; set; }
        public DateTime PublicationDate { get; set; }

        [Required(ErrorMessage = "please enter authorId..")]
        public int AuthorId { get; set; }

        [ForeignKey("AuthorId")]
        public Author? Author { get; set; }
    }
}

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Controllers/AuthorController.cs
using BloggingPlatformApplication.Contexts;
using BloggingPlatformApplication.Interfaces;
using BloggingPlatformApplication.Models;
using BloggingPlatformApplication.Models.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace BloggingPlatformApplication.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly ILogger<AuthorController> _logger;
        private readonly BlogContext _context;

        public AuthorController(IAuthorService authorService, ILogger<AuthorController> logger, BlogContext context)
        {
            _authorService = authorService;
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            List<Author> authors = new List<Author>();
            try
            {
                authors = _authorService.GetAllAuthors().ToList();
                return View(authors);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                _logger.LogInformation("There were no authors");
            }
            return View(authors);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Author author)
        {
            try
            {
                var myAuthor = _authorService.Add(author);
                _logger.LogInformation("Created author record");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                //Logging for programmer
                _logger.LogError("Unable to add author ");
            }
            return View();
        }

        [HttpGet]
        public IActionResult UpdatePhone(int id)
        {
            var auth = _authorService.GetAllAuthors().SingleOrDefault(x => x.AuthorId == id);
            var author = new AuthorDTO { AuthorId = id, Phone = auth.Phone };
            return View(author);
        }
        [HttpPost]
        public IActionResult UpdatePhone(int id, AuthorDTO author)
        {
            try
            {
                var result = _authorService.UpdatePhone(author);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                //Logging for programmer
                _logger.LogError("Unable to upadte author phone... ");
            }
            return View(author);
        }

        [HttpGet]
        public IActionResult UpdateEmail(int id)
        {
            var auth = _authorService.GetAllAuthors().SingleOrDefault(x => x.AuthorId == id);
            var author = new AuthorDTO { AuthorId = id, Email = auth.Email };
            return View(author);
        }
        [HttpPost]
        public IActionResult UpdateEmail(int id, AuthorDTO author)
        {
            try
            {
                var result = _authorService.UpdateEmail(author);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                //Logging for programmer
                _logger.LogError("Unable to update author email... ");
            }
            return View(author);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Author author = _authorService.GetAllAuthors().FirstOrDefault(x => x.AuthorId == id);
            return View(author);
        }
        [HttpPost]
        public IActionResult Delete(int id, Author author)
        {
            author = _authorService.GetAllAuthors().FirstOrDefault(x => x.AuthorId == id);
            _context.authors.Remove(author);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UserLogout(string un)
        {
            HttpContext.Session.Clear();
            return RedirectToAction("UserLogin", "Login");
        }
    }
}

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Controllers/BlogPostController.cs
using BloggingPlatformApplication.Contexts;
using BloggingPlatformApplication.Interfaces;
using BloggingPlatformApplication.Models;
using BloggingPlatformApplication.Models.DTOs;
using BloggingPlatformApplication.Services;
using Microsoft.AspNetCore.Mvc;

namespace BloggingPlatformApplication.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly IBlogPostService _blogPostService;
        private readonly ILogger<BlogPostController> _logger;
        private readonly BlogContext _context;
        private BlogPost? blogPost;

        public BlogPostController(IBlogPostService blogPostService, ILogger<BlogPostController> logger, BlogContext context)
        {
            _blogPostService = blogPostService;
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            List<BlogPost> blogPosts = new List<BlogPost>();
            try
            {
                blogPosts = _blogPostService.GetAllBlogs().ToList();
                return View(blogPosts);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                _logger.LogInformation("There were no blog posts");
            }
            return View(blogPosts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(BlogPost blogPost)
        {
            try
            {
                var blog = _blogPostService.Add(blogPost);
                _logger.LogInformation("Created blog post record..");
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                //Logging for programmer
                _logger.LogError("Unable to add blog post.. ");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var blog = _blogPostService.GetAllBlogs().SingleOrDefault(x => x.AuthorId == id);
            var blogPost = new BlogPostDTO { Id = id, Title = blog.Title, Content = blog.Content };
            return View(blogPost);
        }
        [HttpPost]
        public IActionResult Update(int id, BlogPostDTO blogPost)
        {
            try
            {
                var result = _blogPostService.UpdateTitleAndContent(blogPost);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.Message;
                //Logging for programmer
                _logger.LogError("Unable to upadte author phone... ");
            }
            return View(blogPost);
        }
         [HttpGet]
        public IActionResult Delete(int id)
        {
            BlogPost blogPost = _blogPostService.GetAllBlogs().FirstOrDefault(x => x.Id == id);
            return View(blogPost);
        }
        [HttpPost]
        public IActionResult Delete(int id, BlogPost blogPost)
        {
            blogPost = _blogPostService.GetAllBlogs().FirstOrDefault(x => x.Id == id);
            _context.blogPosts.Remove(blogPost);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Views/BlogPost/Create.cshtml
@model BloggingPlatformApplication.Models.BlogPost

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlogPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationDate" class="control-label"></label>
                <input asp-for="PublicationDate" class="form-control" />
                <span asp-validation-for="PublicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <input asp-for="AuthorId" class="form-control" />
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Views/BlogPost/Delete.cshtml
@model BloggingPlatformApplication.Models.BlogPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Views/BlogPost/Index.cshtml
@model IEnumerable<BloggingPlatformApplication.Models.BlogPost>

@{
    ViewData["Title"] = "Index";
}

<h1>Welcome To BlogPost</h1>

<p>
    <a asp-action="Create">Create New BlogPost</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuthorId)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Update", new {  id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id  })
                </td>
            </tr>
        }
        <div>

            <ul class="nav navbar-nav" style="float:right !important">

                <li class="nav-item">

                    <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="UserLogout">Logout</a>

                </li>

            </ul>

        </div>
    </tbody>
</table>

Day_13/BloggingPlatformSolution/BloggingPlatformApplication/Views/BlogPost/Update.cshtml
@model BloggingPlatformApplication.Models.DTOs.BlogPostDTO

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>BlogPostDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}